// ==UserScript==
// @name         GITL Auto Tester - ChatGPT + Perplexity
// @namespace    https://github.com/MShneur/ghost-in-the-loop
// @version      0.3.1
// @description  One-button mobile tester for first-send and follow-up behavior on ChatGPT and Perplexity.
// @match        https://www.perplexity.ai/*
// @match        https://chatgpt.com/*
// @match        https://chat.openai.com/*
// @run-at       document-idle
// @grant        GM_setClipboard
// @noframes
// ==/UserScript==
(() => {
  'use strict';
  const V='0.3.1', STAGE=6000, ACK=16000, READY=90000, MANUAL=30000, POLL=150;
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const norm=v=>String(v??'').replace(/\s+/g,' ').trim();
  const low=v=>norm(v).toLowerCase();
  const site=()=>/perplexity\.ai$/i.test(location.hostname)?'perplexity':(/chatgpt\.com$|chat\.openai\.com$/i.test(location.hostname)?'chatgpt':'unknown');
  const visible=e=>{if(!e||!e.isConnected)return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>1&&r.height>1&&s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity||1)>0};
  const text=e=>String(e?.value??e?.innerText??e?.textContent??'');
  const state={version:V,site:site(),host:location.hostname,running:false,started:null,finished:null,final:'NOT RUN',baseline:[],followups:[],manual:null};
  let statusEl,runBtn,copyBtn,againBtn;

  function editorSelectors(){return [...(state.site==='chatgpt'?['#prompt-textarea','[data-testid="prompt-textarea"]']:state.site==='perplexity'?['textarea[placeholder*="Ask" i]','[contenteditable="true"][data-lexical-editor="true"]']:[]),'textarea','[contenteditable="true"]','[role="textbox"][contenteditable="true"]','[data-lexical-editor="true"]','div.ProseMirror[contenteditable="true"]']}
  function findEditor(){const set=new Set();for(const q of editorSelectors())try{document.querySelectorAll(q).forEach(e=>{if(!visible(e))return;const a=`${low(e.getAttribute('aria-label'))} ${low(e.getAttribute('placeholder'))}`;if(!/(search settings|search chats|search conversations|rename|filter)/.test(a))set.add(e)})}catch(_){}const all=[...set].sort((a,b)=>scoreEditor(b)-scoreEditor(a));return {editor:all[0]||null,count:all.length}}
  function scoreEditor(e){const r=e.getBoundingClientRect(),a=`${low(e.getAttribute('aria-label'))} ${low(e.getAttribute('placeholder'))}`;let s=r.bottom+r.width/20;if(document.activeElement===e||e.contains?.(document.activeElement))s+=100000;if(/ask|message|prompt|follow|anything|chat/.test(a))s+=8000;if(e.id==='prompt-textarea'||e.getAttribute('data-testid')==='prompt-textarea')s+=12000;if(e.closest('form'))s+=2500;if(r.top>innerHeight*.45)s+=1500;return s}

  function sendSelectors(){return [...(state.site==='chatgpt'?['button[data-testid="send-button"]','button[aria-label*="Send" i]']:state.site==='perplexity'?['button[aria-label*="Submit" i]','button[aria-label*="Send" i]']:[]),'button[type="submit"]','button[data-testid*="send" i]','button[data-testid*="submit" i]','button[aria-label*="send" i]','button[aria-label*="submit" i]','[role="button"][aria-label*="send" i]','[role="button"][aria-label*="submit" i]']}
  const enabled=e=>visible(e)&&!e.disabled&&e.getAttribute('aria-disabled')!=='true'&&!e.hasAttribute('data-disabled');
  function scoreSend(e,ed){const r=e.getBoundingClientRect(),a=`${low(e.getAttribute('aria-label'))} ${low(e.getAttribute('data-testid'))} ${low(e.textContent)}`,t=low(e.getAttribute('type'));let s=0;if(/send message|send prompt|(^|[-_ ])send($|[-_ ])/.test(a))s+=100;if(/submit prompt|(^|[-_ ])submit($|[-_ ])/.test(a))s+=85;if(t==='submit')s+=35;if(ed&&e.closest('form')&&ed.closest('form')===e.closest('form'))s+=65;if(ed){const x=ed.getBoundingClientRect();if(Math.abs(r.left-x.right)<300&&Math.abs(r.top-x.top)<250)s+=25}if(r.top>innerHeight*.45)s+=10;if(/feedback|report|share|upload|voice|mic|search/.test(a))s-=120;return s}
  function sendAuthority(ed=findEditor().editor){const set=new Set();for(const q of sendSelectors())try{document.querySelectorAll(q).forEach(e=>visible(e)&&set.add(e))}catch(_){}const c=[...set].map(e=>({e,score:scoreSend(e,ed)})).filter(x=>x.score>=50).sort((a,b)=>b.score-a.score),en=c.filter(x=>enabled(x.e)),a=en[0],b=en[1],amb=Boolean(a&&b&&a.score-b.score<20);return {button:a&&!amb?a.e:null,candidates:c.length,enabled:en.length,ambiguous:amb,top:a?.score??null}}
  function generating(){const qs=['button[aria-label*="stop" i]','button[data-testid*="stop" i]','[role="button"][aria-label*="stop" i]','button[aria-label*="cancel" i]'];for(const q of qs)try{for(const e of document.querySelectorAll(q)){if(visible(e)&&!/stop sharing|stop listening/i.test(norm(e.getAttribute('aria-label'))))return true}}catch(_){}return false}

  function setValue(e,v){if(e instanceof HTMLTextAreaElement){const s=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;s?s.call(e,v):e.value=v}else if(e instanceof HTMLInputElement){const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;s?s.call(e,v):e.value=v}else{e.textContent='';e.appendChild(document.createTextNode(v))}}
  function input(e,type,data){try{e.dispatchEvent(new InputEvent('input',{bubbles:true,composed:true,inputType:type,data}))}catch(_){e.dispatchEvent(new Event('input',{bubbles:true,composed:true}))}}
  function clear(e){if(!e)return;try{e.focus();setValue(e,'');input(e,'deleteContentBackward',null);e.dispatchEvent(new Event('change',{bubbles:true}))}catch(_){} }
  function selectAll(e){e.focus();if(e instanceof HTMLTextAreaElement||e instanceof HTMLInputElement){e.select?.();return}const s=getSelection();if(!s)return;const r=document.createRange();r.selectNodeContents(e);s.removeAllRanges();s.addRange(r)}
  async function nativeSetter(e,v){e.focus();setValue(e,v);input(e,'insertText',v);e.dispatchEvent(new Event('change',{bubbles:true}))}
  async function execCommand(e,v){e.focus();selectAll(e);let ok=false;try{ok=document.execCommand('insertText',false,v)}catch(_){}if(!ok||!norm(text(e)).includes(v))setValue(e,v);input(e,'insertText',v)}
  async function beforeInput(e,v){e.focus();clear(e);try{e.dispatchEvent(new InputEvent('beforeinput',{bubbles:true,composed:true,cancelable:true,inputType:'insertText',data:v}))}catch(_){}setValue(e,v);input(e,'insertText',v)}
  async function rangeInput(e,v){if(e instanceof HTMLTextAreaElement||e instanceof HTMLInputElement)return nativeSetter(e,v);e.focus();selectAll(e);const s=getSelection(),r=s?.rangeCount?s.getRangeAt(0):null;if(!r)return nativeSetter(e,v);r.deleteContents();const n=document.createTextNode(v);r.insertNode(n);r.setStartAfter(n);r.collapse(true);s.removeAllRanges();s.addRange(r);input(e,'insertText',v)}
  async function pasteInput(e,v){e.focus();clear(e);try{const d=new DataTransfer();d.setData('text/plain',v);e.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,composed:true,cancelable:true,clipboardData:d}))}catch(_){}setValue(e,v);input(e,'insertFromPaste',v)}
  async function compositionInput(e,v){e.focus();clear(e);try{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''}))}catch(_){}setValue(e,v);try{e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:v}))}catch(_){}input(e,'insertCompositionText',v)}
  const methods=[['native-setter',nativeSetter],['execcommand',execCommand],['beforeinput',beforeInput],['range-input',rangeInput],['paste-input',pasteInput],['composition-input',compositionInput]];

  async function waitSend(ed){const end=Date.now()+STAGE;let a;while(Date.now()<end){a=sendAuthority(ed);if(a.ambiguous)return {ok:false,reason:'AMBIGUOUS_SEND',...a};if(a.button)return {ok:true,...a};await sleep(POLL)}a=sendAuthority(ed);return {ok:false,reason:a.ambiguous?'AMBIGUOUS_SEND':'SEND_DISABLED_TIMEOUT',...a}}
  async function waitAck(ed,marker,value){const end=Date.now()+ACK;while(Date.now()<end){const cur=findEditor().editor||ed,ct=norm(text(cur)),cleared=ct!==norm(value)&&!ct.includes(marker),outside=cleared&&norm(document.body?.innerText).includes(marker),active=generating();if(cleared&&(outside||active))return {ok:true,cleared,outside,active,replaced:cur!==ed};await sleep(POLL)}const cur=findEditor().editor||ed;return {ok:false,cleared:!norm(text(cur)).includes(marker),outside:norm(document.body?.innerText).includes(marker),active:generating(),replaced:cur!==ed}}
  async function waitReady(){const end=Date.now()+READY;let seen=generating(),quiet=null;while(Date.now()<end){const active=generating();if(active){seen=true;quiet=null}else{if(quiet===null)quiet=Date.now();if(findEditor().editor&&Date.now()-quiet>=(seen?1000:2500))return {ok:true,seen}}await sleep(250)}return {ok:false,seen,active:generating()}}

  async function attempt(name,fn,phase){const f=findEditor(),r={phase,method:name,result:'FAIL',reason:null,editorCount:f.count,stageVisible:false,send:null,clicked:false,ack:null,ready:null};if(!f.editor){r.reason='NO_EDITOR';return r}const marker=`GITL-${phase}-${Date.now().toString(36)}-${name}`,value=`${marker}. Reply only: OK`;clear(f.editor);await sleep(120);try{await fn(f.editor,value)}catch(e){r.reason='STAGE_EXCEPTION';r.error=String(e?.message||e).slice(0,160);return r}await sleep(220);const ed=findEditor().editor||f.editor;r.stageVisible=norm(text(ed)).includes(marker);if(!r.stageVisible){r.reason='TEXT_NOT_VISIBLE';clear(ed);return r}const s=await waitSend(ed);r.send={candidates:s.candidates,enabled:s.enabled,ambiguous:s.ambiguous,top:s.top};if(!s.ok){r.reason=s.reason;if(s.reason!=='AMBIGUOUS_SEND')clear(findEditor().editor||ed);return r}s.button.click();r.clicked=true;r.ack=await waitAck(ed,marker,value);if(!r.ack.ok){r.result='UNCERTAIN';r.reason='SEND_ACK_TIMEOUT';return r}r.ready=await waitReady();if(!r.ready.ok){r.result='UNCERTAIN';r.reason='POST_SEND_STATE_TIMEOUT';return r}r.result='PASS';return r}

  async function manualCheck(name,fn){const f=findEditor();if(!f.editor)return {needed:false,reason:'NO_EDITOR'};const marker=`GITL-MANUAL-${Date.now().toString(36)}`;clear(f.editor);await fn(f.editor,`${marker} type-check`);await sleep(250);let ed=findEditor().editor||f.editor,before=sendAuthority(ed);if(before.button){clear(ed);return {needed:false,beforeEnabled:true,afterEnabled:true}}setStatus('Type ONE normal character. Do not press Send.');const start=norm(text(ed)),end=Date.now()+MANUAL;let typed=false;while(Date.now()<end){ed=findEditor().editor||ed;if(norm(text(ed))!==start){typed=true;break}await sleep(POLL)}const after=sendAuthority(ed);clear(ed);return {needed:true,method:name,typed,beforeEnabled:false,afterEnabled:Boolean(after.button),afterAmbiguous:after.ambiguous,afterEnabledCount:after.enabled}}

  async function run(){if(state.running)return;state.running=true;state.started=new Date().toISOString();state.finished=null;state.final='RUNNING';state.baseline=[];state.followups=[];state.manual=null;runBtn.disabled=true;copyBtn.hidden=true;againBtn.hidden=true;try{let base=null;for(const [name,fn] of methods){setStatus(`First-send: ${name}`);const r=await attempt(name,fn,'BASE');state.baseline.push(r);if(r.result==='UNCERTAIN'||r.reason==='AMBIGUOUS_SEND'){state.final=`STOPPED: ${r.reason}`;return}if(r.result==='PASS'){base=[name,fn];break}}if(!base){state.final='FAIL: NO SAFE FIRST-SEND METHOD';return}const order=[base,...methods.filter(([n])=>n!==base[0])];for(const [name,fn] of order){setStatus(`Follow-up: ${name}`);const r=await attempt(name,fn,'FOLLOW');state.followups.push(r);if(r.result==='UNCERTAIN'||r.reason==='AMBIGUOUS_SEND'){state.final=`STOPPED: FOLLOW-UP ${r.reason}`;return}if(r.result==='PASS'){state.final=`PASS: FOLLOW-UP WORKS (${name})`;return}}const blocked=state.followups.find(x=>x.stageVisible&&x.reason==='SEND_DISABLED_TIMEOUT');if(blocked){const m=methods.find(([n])=>n===blocked.method);if(m)state.manual=await manualCheck(m[0],m[1])}if(state.manual?.needed&&state.manual.afterEnabled)state.final='FAIL: TEXT VISIBLE, BUT HOST STATE COMMITS ONLY AFTER REAL KEYSTROKE';else if(state.manual?.needed&&state.manual.typed)state.final='FAIL: SEND STILL DISABLED AFTER REAL KEYSTROKE';else state.final='FAIL: FOLLOW-UP NEVER ENABLED A SAFE SEND'}catch(e){state.final=`TESTER ERROR: ${String(e?.message||e).slice(0,160)}`}finally{state.running=false;state.finished=new Date().toISOString();runBtn.disabled=false;copyBtn.hidden=false;againBtn.hidden=false;setStatus(state.final)}}

  function report(){const l=[`GITL AUTO BOTH v${V}`,`Host: ${state.host} (${state.site})`,`Final: ${state.final}`,`Started: ${state.started||'-'}`,`Finished: ${state.finished||'-'}`,''];for(const x of state.baseline)l.push(`BASE | ${x.method} | ${x.result} | ${x.reason||'OK'} | stage=${x.stageVisible?'Y':'N'} | send=${x.send?.enabled??0}/${x.send?.candidates??0}`);for(const x of state.followups)l.push(`FOLLOW | ${x.method} | ${x.result} | ${x.reason||'OK'} | stage=${x.stageVisible?'Y':'N'} | send=${x.send?.enabled??0}/${x.send?.candidates??0}`);if(state.manual)l.push(`MANUAL | ${JSON.stringify(state.manual)}`);l.push('','DETAIL JSON:',JSON.stringify(state,null,2));return l.join('\n')}
  async function copyReport(){const r=report();try{if(typeof GM_setClipboard==='function'){GM_setClipboard(r,'text');setStatus('Report copied. Paste it here.');return}}catch(_){}try{await navigator.clipboard.writeText(r);setStatus('Report copied. Paste it here.')}catch(_){setStatus('Copy blocked. Run __GITL_AUTO_REPORT__() in console.')}}
  function setStatus(s){if(statusEl)statusEl.textContent=s}
  function mount(){if(document.getElementById('gitl-auto-both-host'))return;const h=document.createElement('div');h.id='gitl-auto-both-host';h.style.cssText='position:fixed;right:8px;bottom:8px;z-index:2147483647;width:min(300px,calc(100vw - 16px));max-width:300px;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif';document.documentElement.appendChild(h);const sh=h.attachShadow({mode:'open'});sh.innerHTML=`<style>*{box-sizing:border-box}.c{background:#111;color:#fff;border:1px solid #444;border-radius:12px;padding:10px;box-shadow:0 8px 26px #0006;font-size:13px}.t{font-weight:700;margin-bottom:6px}.s{background:#1b1b1b;border-radius:8px;padding:8px;margin-bottom:8px;max-height:82px;overflow:auto;word-break:break-word}.r{display:flex;gap:6px;flex-wrap:wrap}button{border:0;border-radius:9px;padding:10px 12px;font-weight:700;font-size:13px;min-height:40px;cursor:pointer;flex:1}button:disabled{opacity:.5}button[hidden]{display:none}.h{font-size:11px;color:#bbb;margin-top:7px}</style><div class="c"><div class="t">GITL Auto Tester v${V}</div><div class="s" id="s">Ready on ${state.site}. Press RUN once.</div><div class="r"><button id="run">RUN AUTO TEST</button><button id="copy" hidden>COPY REPORT</button><button id="again" hidden>RUN AGAIN</button></div><div class="h">Same script for ChatGPT and Perplexity. It stops rather than retrying an uncertain send.</div></div>`;statusEl=sh.getElementById('s');runBtn=sh.getElementById('run');copyBtn=sh.getElementById('copy');againBtn=sh.getElementById('again');runBtn.onclick=run;copyBtn.onclick=copyReport;againBtn.onclick=run}
  window.__GITL_AUTO_REPORT__=report;mount();
})();
