// ==UserScript==
// @name         GITL Site-Aware Auto Field Tester
// @namespace    https://github.com/MShneur/ghost-in-the-loop
// @version      0.2.1
// @description  One-button ChatGPT/Perplexity follow-up tester with fallback staging, hard timeouts, DOM-change diagnostics, and one copyable report.
// @match        https://www.perplexity.ai/*
// @match        https://chatgpt.com/*
// @match        https://chat.openai.com/*
// @run-at       document-idle
// @grant        GM_setClipboard
// @noframes
// ==/UserScript==
(() => {
  'use strict';
  const V='0.2.1', STAGE=5500, ACK=14000, GEN=45000, MANUAL=22000;
  const sleep=ms=>new Promise(r=>setTimeout(r,ms)), now=()=>new Date().toISOString();
  const norm=v=>String(v||'').replace(/\s+/g,' ').trim(), low=v=>norm(v).toLowerCase();
  const platform=()=>/perplexity\.ai$/i.test(location.hostname)?'perplexity':(/chatgpt\.com$|chat\.openai\.com$/i.test(location.hostname)?'chatgpt':'unknown');
  const vis=e=>{if(!e||!e.isConnected)return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>1&&r.height>1&&s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity||1)>0};
  const text=e=>String(e?.value??e?.innerText??e?.textContent??'');
  const ids=new WeakMap();let nextId=1,mutSeq=0;const muts=[];
  const id=e=>{if(!e)return null;if(!ids.has(e))ids.set(e,nextId++);return ids.get(e)};
  const sig=e=>{if(!e)return null;const r=e.getBoundingClientRect();return {id:id(e),tag:(e.tagName||'').toLowerCase(),role:norm(e.getAttribute?.('role'))||null,aria:norm(e.getAttribute?.('aria-label'))||null,ph:norm(e.getAttribute?.('placeholder'))||null,testid:norm(e.getAttribute?.('data-testid'))||null,type:norm(e.getAttribute?.('type'))||null,ce:norm(e.getAttribute?.('contenteditable'))||null,disabled:Boolean(e.disabled)||e.getAttribute?.('aria-disabled')==='true'||e.hasAttribute?.('data-disabled'),cls:(typeof e.className==='string'?norm(e.className).split(' ').slice(0,5).join(' '):null),box:[Math.round(r.x),Math.round(r.y),Math.round(r.width),Math.round(r.height)]}};

  function editorSelectors(){return [...(platform()==='chatgpt'?['#prompt-textarea','[data-testid="prompt-textarea"]']:platform()==='perplexity'?['textarea[placeholder*="Ask" i]','[contenteditable="true"][data-lexical-editor="true"]']:[]),'textarea','[contenteditable="true"]','[role="textbox"][contenteditable="true"]','[data-lexical-editor="true"]','div.ProseMirror[contenteditable="true"]']}
  function editors(){const s=new Set();for(const q of editorSelectors())try{document.querySelectorAll(q).forEach(e=>{if(!vis(e))return;const a=`${low(e.getAttribute('aria-label'))} ${low(e.getAttribute('placeholder'))}`;if(!/(search settings|rename|filter|search chats|search conversations)/.test(a))s.add(e)})}catch(_){}return [...s]}
  function editorScore(e){const r=e.getBoundingClientRect(),a=`${low(e.getAttribute('aria-label'))} ${low(e.getAttribute('placeholder'))}`;let n=r.bottom+(r.width/20);if(document.activeElement===e||e.contains?.(document.activeElement))n+=1e5;if(/ask|message|prompt|follow|anything|chat/.test(a))n+=8000;if(e.id==='prompt-textarea'||e.getAttribute('data-testid')==='prompt-textarea')n+=12000;if(e.closest('form'))n+=2500;if(r.top>innerHeight*.45)n+=1500;return n}
  function findEditor(){const all=editors().sort((a,b)=>editorScore(b)-editorScore(a));return {editor:all[0]||null,count:all.length,all}}

  function sendSelectors(){return [...(platform()==='chatgpt'?['button[data-testid="send-button"]','button[aria-label*="Send" i]']:platform()==='perplexity'?['button[aria-label*="Submit" i]','button[aria-label*="Send" i]']:[]),'button[type="submit"]','button[data-testid*="send" i]','button[data-testid*="submit" i]','button[aria-label*="send" i]','button[aria-label*="submit" i]','[role="button"][aria-label*="send" i]','[role="button"][aria-label*="submit" i]']}
  const enabled=e=>Boolean(e)&&vis(e)&&!e.disabled&&e.getAttribute('aria-disabled')!=='true'&&!e.hasAttribute('data-disabled');
  function sendScore(e,ed){if(!vis(e))return -1e9;const r=e.getBoundingClientRect(),a=`${low(e.getAttribute('aria-label'))} ${low(e.getAttribute('data-testid'))} ${low(e.textContent)}`,t=low(e.getAttribute('type'));let n=0;if(/send message|send prompt|(^|[-_ ])send($|[-_ ])/.test(a))n+=100;if(/submit prompt|(^|[-_ ])submit($|[-_ ])/.test(a))n+=85;if(t==='submit')n+=35;if(ed&&e.closest('form')&&ed.closest('form')===e.closest('form'))n+=65;if(ed){const x=ed.getBoundingClientRect();if(Math.abs(r.left-x.right)<300&&Math.abs(r.top-x.top)<250)n+=25}if(r.top>innerHeight*.45)n+=10;if(/feedback|report|share|upload|voice|mic|search/.test(a))n-=120;return n}
  function sends(ed=findEditor().editor){const s=new Set();for(const q of sendSelectors())try{document.querySelectorAll(q).forEach(e=>vis(e)&&s.add(e))}catch(_){}return [...s].map(e=>({e,score:sendScore(e,ed)})).filter(x=>x.score>=50).sort((a,b)=>b.score-a.score)}
  function authority(ed=findEditor().editor){const c=sends(ed),en=c.filter(x=>enabled(x.e)),a=en[0],b=en[1],amb=Boolean(a&&b&&a.score-b.score<20);return {c,en,amb,button:a&&!amb?a.e:null,count:c.length,enabledCount:en.length,top:a?.score??null}}

  function genEls(){const s=new Set(),qs=['button[aria-label*="stop" i]','button[data-testid*="stop" i]','[role="button"][aria-label*="stop" i]','button[aria-label*="cancel" i]'];for(const q of qs)try{document.querySelectorAll(q).forEach(e=>vis(e)&&s.add(e))}catch(_){}return [...s].filter(e=>!/stop sharing|stop listening/i.test(norm(e.getAttribute('aria-label'))))}
  const generating=()=>genEls().length>0;
  function site(){const f=findEditor(),ss=sends(f.editor),g=genEls();return {at:now(),url:`${location.origin}${location.pathname}`,title:document.title,platform:platform(),viewport:[innerWidth,innerHeight,devicePixelRatio||1],editorCount:f.count,editors:f.all.slice(0,4).map(sig),sendCount:ss.length,sends:ss.slice(0,6).map(x=>({score:x.score,...sig(x.e)})),generationCount:g.length,generation:g.slice(0,4).map(sig)}}

  function related(node,qs){if(!(node instanceof Element))return false;try{return qs.some(q=>node.matches(q)||node.querySelector?.(q))}catch(_){return false}}
  const mo=new MutationObserver(rs=>{for(const r of rs){const t=r.target instanceof Element?r.target:r.target?.parentElement,add=[...(r.addedNodes||[])].filter(n=>n instanceof Element),rem=[...(r.removedNodes||[])].filter(n=>n instanceof Element),er=related(t,editorSelectors())||add.some(n=>related(n,editorSelectors()))||rem.some(n=>related(n,editorSelectors())),sr=related(t,sendSelectors())||add.some(n=>related(n,sendSelectors()))||rem.some(n=>related(n,sendSelectors()));if(!er&&!sr&&r.type!=='attributes')continue;muts.push({seq:++mutSeq,at:now(),kind:r.type,attr:r.attributeName||null,target:t?sig(t):null,editor:er,send:sr});if(muts.length>80)muts.shift()}});
  try{mo.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['disabled','aria-disabled','aria-label','data-testid','contenteditable','class']})}catch(_){}
  const mutSummary=s=>{const x=muts.filter(m=>m.seq>s);return {count:x.length,attrs:x.filter(m=>m.kind==='attributes').length,child:x.filter(m=>m.kind==='childList').length,editor:x.filter(m=>m.editor).length,send:x.filter(m=>m.send).length,samples:x.slice(-10)}};

  function setVal(e,v){if(e instanceof HTMLTextAreaElement){const s=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;s?s.call(e,v):e.value=v}else if(e instanceof HTMLInputElement){const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;s?s.call(e,v):e.value=v}else{e.textContent='';e.appendChild(document.createTextNode(v))}}
  function input(e,type,data){try{e.dispatchEvent(new InputEvent('input',{bubbles:true,composed:true,inputType:type,data}))}catch(_){e.dispatchEvent(new Event('input',{bubbles:true,composed:true}))}}
  function clear(e){if(!e)return;try{e.focus();setVal(e,'');input(e,'deleteContentBackward',null);e.dispatchEvent(new Event('change',{bubbles:true}))}catch(_){} }
  function selectAll(e){e.focus();if(e instanceof HTMLTextAreaElement||e instanceof HTMLInputElement){e.select?.();return}const s=getSelection();if(!s)return;const r=document.createRange();r.selectNodeContents(e);s.removeAllRanges();s.addRange(r)}
  async function nativeSetter(e,v){e.focus();setVal(e,v);input(e,'insertText',v);e.dispatchEvent(new Event('change',{bubbles:true}))}
  async function execCommand(e,v){e.focus();selectAll(e);let ok=false;try{ok=document.execCommand('insertText',false,v)}catch(_){}if(!ok||!norm(text(e)).includes(v))setVal(e,v);input(e,'insertText',v)}
  async function beforeInput(e,v){e.focus();clear(e);try{e.dispatchEvent(new InputEvent('beforeinput',{bubbles:true,composed:true,cancelable:true,inputType:'insertText',data:v}))}catch(_){}setVal(e,v);input(e,'insertText',v)}
  async function rangeInput(e,v){e.focus();if(e instanceof HTMLTextAreaElement||e instanceof HTMLInputElement)return nativeSetter(e,v);selectAll(e);const s=getSelection(),r=s?.rangeCount?s.getRangeAt(0):null;if(!r)return nativeSetter(e,v);r.deleteContents();const n=document.createTextNode(v);r.insertNode(n);r.setStartAfter(n);r.collapse(true);s.removeAllRanges();s.addRange(r);input(e,'insertText',v)}
  async function pasteInput(e,v){e.focus();clear(e);try{const d=new DataTransfer();d.setData('text/plain',v);e.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,composed:true,cancelable:true,clipboardData:d}))}catch(_){}setVal(e,v);input(e,'insertFromPaste',v)}
  async function keyCycle(e,v){e.focus();clear(e);try{e.dispatchEvent(new KeyboardEvent('keydown',{bubbles:true,composed:true,key:'a'}))}catch(_){}setVal(e,v);input(e,'insertText',v);try{e.dispatchEvent(new KeyboardEvent('keyup',{bubbles:true,composed:true,key:'a'}))}catch(_){}e.dispatchEvent(new Event('change',{bubbles:true}))}
  async function composition(e,v){e.focus();clear(e);try{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''}));e.dispatchEvent(new CompositionEvent('compositionupdate',{bubbles:true,data:v}))}catch(_){}setVal(e,v);try{e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:v}))}catch(_){}input(e,'insertCompositionText',v)}
  const methods=[['native-setter',nativeSetter],['execcommand',execCommand],['beforeinput',beforeInput],['range-input',rangeInput],['paste-input',pasteInput],['keycycle-input',keyCycle],['composition-input',composition]];

  const compact=a=>({count:a.count,enabledCount:a.enabledCount,ambiguous:a.amb,top:a.top,candidates:a.c.slice(0,5).map(x=>({score:x.score,...sig(x.e)}))});
  async function waitSend(ed){const end=Date.now()+STAGE;let a;while(Date.now()<end){a=authority(ed);if(a.button)return {ok:true,...a};if(a.amb)return {ok:false,reason:'AMBIGUOUS_SEND',...a};await sleep(140)}a=authority(ed);return {ok:false,reason:a.amb?'AMBIGUOUS_SEND':'SEND_DISABLED_TIMEOUT',...a}}
  async function waitAck(ed,marker,value){const end=Date.now()+ACK;while(Date.now()<end){const cur=findEditor().editor||ed,ct=norm(text(cur)),cleared=ct!==norm(value)&&!ct.includes(marker),outside=cleared&&norm(document.body?.innerText).includes(marker),active=generating(),replaced=cur!==ed;if(cleared&&(outside||active))return {ok:true,cleared,outside,active,replaced};await sleep(150)}const cur=findEditor().editor||ed;return {ok:false,cleared:!norm(text(cur)).includes(marker),outside:norm(document.body?.innerText).includes(marker),active:generating(),replaced:cur!==ed}}
  async function waitGeneration(){const start=Date.now();let seen=generating(),quiet=null;while(Date.now()-start<GEN){const a=generating();if(a){seen=true;quiet=null}else{if(quiet===null)quiet=Date.now();if(findEditor().editor&&Date.now()-quiet>=(seen?1000:2500))return {ok:true,seen,ms:Date.now()-start}}await sleep(250)}return {ok:false,seen,active:generating(),ms:Date.now()-start}}

  const state={version:V,platform:platform(),host:location.hostname,startedAt:null,finishedAt:null,final:'NOT RUN',tests:[],siteStart:null,siteEnd:null,manual:null,stopped:false};
  let host,shadow,status,play,copy,again;
  const setStatus=s=>{if(status)status.textContent=s};
  async function runOne(name,fn,index,repeat=false){setStatus(`Test ${index}: ${name}${repeat?' follow-up':''}`);const started=Date.now(),ms=mutSeq,before=site(),f=findEditor(),rec={index,method:name,repeat,result:'FAIL',reason:null,elapsed:null,marker:null,before,afterStage:null,afterSend:null,editorBefore:id(f.editor),editorAfter:null,editorReplaced:false,stageVisible:false,send:null,sent:false,ack:null,generation:null,mutations:null};state.tests.push(rec);if(!f.editor){rec.reason='NO_EDITOR';rec.mutations=mutSummary(ms);rec.elapsed=Date.now()-started;return rec}const marker=`GITL-${Date.now().toString(36)}-${index}-${name}${repeat?'-R':''}`,value=`${marker}. Reply only: OK`;rec.marker=marker;clear(f.editor);await sleep(120);try{await fn(f.editor,value)}catch(e){rec.reason='STAGE_EXCEPTION';rec.error=String(e?.message||e).slice(0,160);rec.mutations=mutSummary(ms);rec.elapsed=Date.now()-started;return rec}await sleep(220);const f2=findEditor(),ed=f2.editor||f.editor;rec.editorAfter=id(ed);rec.editorReplaced=ed!==f.editor;rec.stageVisible=norm(text(ed)).includes(marker);rec.afterStage=site();if(!rec.stageVisible){rec.reason='TEXT_NOT_VISIBLE';clear(ed);rec.mutations=mutSummary(ms);rec.elapsed=Date.now()-started;return rec}const a=await waitSend(ed);rec.send=compact(a);if(!a.ok){rec.reason=a.reason;clear(findEditor().editor||ed);rec.mutations=mutSummary(ms);rec.elapsed=Date.now()-started;return rec}a.button.click();rec.sent=true;rec.ack=await waitAck(ed,marker,value);rec.afterSend=site();if(!rec.ack.ok){rec.result='UNCERTAIN';rec.reason='SEND_ACK_TIMEOUT';rec.mutations=mutSummary(ms);rec.elapsed=Date.now()-started;return rec}rec.generation=await waitGeneration();if(!rec.generation.ok){rec.reason=rec.generation.active?'GENERATION_TIMEOUT_ACTIVE':'GENERATION_TIMEOUT';rec.mutations=mutSummary(ms);rec.elapsed=Date.now()-started;return rec}rec.result='PASS';rec.mutations=mutSummary(ms);rec.elapsed=Date.now()-started;return rec}
  async function manualCheck(){const f=findEditor();if(!f.editor)return {needed:false,reason:'NO_EDITOR'};const marker=`GITL-MANUAL-${Date.now().toString(36)}`;clear(f.editor);await nativeSetter(f.editor,`${marker} type-check`);await sleep(200);const a=authority(findEditor().editor||f.editor);if(a.button){clear(findEditor().editor||f.editor);return {needed:false,beforeEnabled:true,afterEnabled:true}}setStatus('Manual check: type ONE normal character. Do not press Send.');const start=norm(text(findEditor().editor||f.editor)),end=Date.now()+MANUAL;let typed=false;while(Date.now()<end){if(norm(text(findEditor().editor||f.editor))!==start){typed=true;break}await sleep(140)}const b=authority(findEditor().editor||f.editor);clear(findEditor().editor||f.editor);return {needed:true,typed,beforeEnabled:false,afterEnabled:Boolean(b.button),after:compact(b)}}
  async function run(){if(state.running)return;state.running=true;state.startedAt=now();state.finishedAt=null;state.final='RUNNING';state.tests=[];state.manual=null;state.stopped=false;state.siteStart=site();play.disabled=true;copy.hidden=true;again.hidden=true;try{const passes=[];let i=1;for(const [n,f] of methods){const r=await runOne(n,f,i++);if(r.result==='PASS')passes.push([n,f]);if(r.result==='UNCERTAIN'){state.stopped=true;state.final='STOPPED: SEND UNCERTAIN';break}if(r.reason==='GENERATION_TIMEOUT_ACTIVE'){state.stopped=true;state.final='STOPPED: GENERATION ACTIVE';break}await sleep(500)}if(!state.stopped){for(const [n,f] of passes.slice(0,3)){const r=await runOne(n,f,i++,true);if(r.result==='UNCERTAIN'){state.stopped=true;state.final='STOPPED: FOLLOW-UP SEND UNCERTAIN';break}if(r.reason==='GENERATION_TIMEOUT_ACTIVE'){state.stopped=true;state.final='STOPPED: FOLLOW-UP GENERATION ACTIVE';break}await sleep(500)}}if(!state.stopped){const first=state.tests.filter(x=>!x.repeat&&x.result==='PASS'),repeat=state.tests.filter(x=>x.repeat&&x.result==='PASS'),disabled=state.tests.some(x=>x.stageVisible&&x.reason==='SEND_DISABLED_TIMEOUT');if(!repeat.length&&disabled)state.manual=await manualCheck();state.final=!first.length?'NO PROGRAMMATIC METHOD ENABLED RELIABLE SEND':!repeat.length?'FIRST-PASS ONLY: FOLLOW-UP UNRELIABLE':`FOLLOW-UP METHODS FOUND: ${repeat.map(x=>x.method).join(', ')}`}}catch(e){state.final=`TESTER ERROR: ${String(e?.message||e).slice(0,120)}`}finally{state.siteEnd=site();state.finishedAt=now();state.running=false;play.disabled=false;copy.hidden=false;again.hidden=false;setStatus(state.final)}}
  function report(){const l=[`GITL SITE-AWARE FIELD TEST v${V}`,`Host: ${state.host} (${state.platform})`,`Final: ${state.final}`,`Started: ${state.startedAt||'-'}`,`Finished: ${state.finishedAt||'-'}`,''];for(const t of state.tests)l.push(`#${t.index} | ${t.method}${t.repeat?' FOLLOW-UP':''} | ${t.result} | ${t.reason||'OK'} | stage=${t.stageVisible?'Y':'N'} | editor=${t.editorBefore}->${t.editorAfter} | send=${t.send?.enabledCount??0}/${t.send?.count??0} | mut=${t.mutations?.count??0} | ${t.elapsed??0}ms`);if(state.manual)l.push(`Manual: ${JSON.stringify(state.manual)}`);l.push('','DETAIL JSON:',JSON.stringify(state,null,2));return l.join('\n')}
  async function copyReport(){const r=report();try{if(typeof GM_setClipboard==='function'){GM_setClipboard(r,'text');setStatus('Report copied. Paste it into ChatGPT.');return}}catch(_){}try{await navigator.clipboard.writeText(r);setStatus('Report copied. Paste it into ChatGPT.')}catch(_){setStatus('Copy blocked. Use window.__GITL_FIELD_REPORT__()')}}
  function mount(){if(document.getElementById('gitl-site-aware-field-tester-host'))return;host=document.createElement('div');host.id='gitl-site-aware-field-tester-host';host.style.cssText='position:fixed;right:8px;bottom:8px;z-index:2147483647;width:min(300px,calc(100vw - 16px));max-width:300px;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif';document.documentElement.appendChild(host);shadow=host.attachShadow({mode:'open'});shadow.innerHTML=`<style>*{box-sizing:border-box}.c{background:#111;color:#fff;border:1px solid #444;border-radius:12px;padding:10px;box-shadow:0 8px 26px #0006;font-size:13px}.t{font-weight:700;margin-bottom:6px}.s{background:#1b1b1b;border-radius:8px;padding:8px;margin-bottom:8px;max-height:76px;overflow:auto;word-break:break-word}.r{display:flex;gap:6px;flex-wrap:wrap}button{border:0;border-radius:9px;padding:10px 12px;font-weight:700;font-size:13px;min-height:40px;cursor:pointer;flex:1}button:disabled{opacity:.5}button[hidden]{display:none}.h{font-size:11px;color:#bbb;margin-top:7px}</style><div class="c"><div class="t">GITL Field Tester v${V}</div><div class="s" id="s">Ready on ${platform()}. Press PLAY once.</div><div class="r"><button id="p">PLAY</button><button id="c" hidden>COPY REPORT</button><button id="a" hidden>RUN AGAIN</button></div><div class="h">Automatic. If a Send result is uncertain, it stops instead of risking a duplicate.</div></div>`;status=shadow.getElementById('s');play=shadow.getElementById('p');copy=shadow.getElementById('c');again=shadow.getElementById('a');play.onclick=run;copy.onclick=copyReport;again.onclick=run}
  window.__GITL_FIELD_REPORT__=report;mount();
})();